name: meddy_core
description: Meddy data layer
version: 1.0.0

environment:
  sdk: ^3.8.1
resolution: workspace

dependencies:
  drift: ^2.28.1
  sqlite3: ^2.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  drift_dev: ^2.28.1
  build_runner: ^2.6.0
